from datetime import UTC, datetime
from enum import StrEnum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field


class WorkflowStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SIGNAL_GENERATION = "SIGNAL_GENERATION"
    BACKTESTING = "BACKTESTING"
    PERSISTING_ARTIFACTS = "PERSISTING_ARTIFACTS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ResearchWorkflowDefinition(BaseModel):
    """Configuration for a multi-stage research workflow."""

    model_config = ConfigDict(frozen=True)

    workflow_id: UUID = Field(default_factory=uuid4)
    name: str
    description: str | None = None
    signal_ids: list[UUID]
    backtest_id: UUID
    parameters: dict[str, Any] = Field(default_factory=dict)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ResearchRun(BaseModel):
    """Audit record for a complete research workflow execution."""

    run_id: UUID = Field(default_factory=uuid4)
    workflow_id: UUID
    correlation_id: UUID
    status: WorkflowStatus = WorkflowStatus.PENDING
    started_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    completed_at: datetime | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class WorkflowStage(BaseModel):
    """State tracking for an individual stage in the workflow."""

    run_id: UUID
    stage_name: str
    status: WorkflowStatus
    started_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    completed_at: datetime | None = None
    error: str | None = None


class WorkflowArtifact(BaseModel):
    """Pointer to final research outputs generated by the workflow."""

    artifact_id: UUID = Field(default_factory=uuid4)
    run_id: UUID
    artifact_type: str
    data: dict[str, Any]
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class WorkflowSnapshot(BaseModel):
    """Immutable state of the entire workflow for reproducibility."""

    model_config = ConfigDict(frozen=True)

    snapshot_id: UUID = Field(default_factory=uuid4)
    run_id: UUID
    workflow_definition: ResearchWorkflowDefinition
    execution_state: dict[str, Any]
    captured_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
